LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := google.xml
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_PRODUCT_OUT_ROOT)/etc/preferred-apps
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)